services:
  postgres:
    image: postgres:latest
    container_name: petshop_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata_petshop:/var/lib/postgresql/data
      - ./init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./исходные данные:/docker-entrypoint-initdb.d/исходные данные
      - ./sql:/docker-entrypoint-initdb.d/sql
      - ./mock_data_analysis:/mock_data_analysis
    networks:
      - petshop_net
    command: postgres
    restart: unless-stopped

volumes:
  pgdata_petshop:


networks:
  petshop_net:
