SELECT
    COUNT(*) FILTER (WHERE sale_seller_id IS NULL) AS null_sale_seller_id,
    COUNT(*) FILTER (WHERE product_rating IS NULL) AS null_or_empty_product_rating,
    COUNT(*) FILTER (WHERE product_reviews IS NULL) AS null_or_empty_product_reviews,
    COUNT(*) FILTER (WHERE sale_product_id IS NULL) AS null_sale_product_id,
    COUNT(*) FILTER (WHERE sale_quantity IS NULL) AS null_sale_quantity,
    COUNT(*) FILTER (WHERE sale_total_price IS NULL) AS null_sale_total_price,
    COUNT(*) FILTER (WHERE product_weight IS NULL) AS null_product_weight,
    COUNT(*) FILTER (WHERE product_price IS NULL) AS null_product_price,
    COUNT(*) FILTER (WHERE product_quantity IS NULL) AS null_product_quantity,
    COUNT(*) FILTER (WHERE customer_age IS NULL) AS null_customer_age,
    COUNT(*) FILTER (WHERE sale_customer_id IS NULL) AS null_sale_customer_id,
    COUNT(*) FILTER (WHERE id IS NULL) AS null_id,
    COUNT(*) FILTER (WHERE seller_country IS NULL OR seller_country = '') AS null_or_empty_seller_country,
    COUNT(*) FILTER (WHERE seller_postal_code IS NULL OR seller_postal_code = '') AS null_or_empty_seller_postal_code,
    COUNT(*) FILTER (WHERE product_name IS NULL OR product_name = '') AS null_or_empty_product_name,
    COUNT(*) FILTER (WHERE product_category IS NULL OR product_category = '') AS null_or_empty_product_category,
    COUNT(*) FILTER (WHERE sale_date IS NULL) AS null_sale_date,
    COUNT(*) FILTER (WHERE store_name IS NULL OR store_name = '') AS null_or_empty_store_name,
    COUNT(*) FILTER (WHERE store_location IS NULL OR store_location = '') AS null_or_empty_store_location,
    COUNT(*) FILTER (WHERE store_city IS NULL OR store_city = '') AS null_or_empty_store_city,
    COUNT(*) FILTER (WHERE store_state IS NULL OR store_state = '') AS null_or_empty_store_state,
    COUNT(*) FILTER (WHERE store_country IS NULL OR store_country = '') AS null_or_empty_store_country,
    COUNT(*) FILTER (WHERE store_phone IS NULL OR store_phone = '') AS null_or_empty_store_phone,
    COUNT(*) FILTER (WHERE store_email IS NULL OR store_email = '') AS null_or_empty_store_email,
    COUNT(*) FILTER (WHERE pet_category IS NULL OR pet_category = '') AS null_or_empty_pet_category,
    COUNT(*) FILTER (WHERE product_color IS NULL OR product_color = '') AS null_or_empty_product_color,
    COUNT(*) FILTER (WHERE product_size IS NULL OR product_size = '') AS null_or_empty_product_size,
    COUNT(*) FILTER (WHERE product_brand IS NULL OR product_brand = '') AS null_or_empty_product_brand,
    COUNT(*) FILTER (WHERE product_material IS NULL OR product_material = '') AS null_or_empty_product_material,
    COUNT(*) FILTER (WHERE product_description IS NULL OR product_description = '') AS null_or_empty_product_description,
    COUNT(*) FILTER (WHERE product_release_date IS NULL) AS null_product_release_date,
    COUNT(*) FILTER (WHERE product_expiry_date IS NULL) AS null_product_expiry_date,
    COUNT(*) FILTER (WHERE supplier_name IS NULL OR supplier_name = '') AS null_or_empty_supplier_name,
    COUNT(*) FILTER (WHERE supplier_contact IS NULL OR supplier_contact = '') AS null_or_empty_supplier_contact,
    COUNT(*) FILTER (WHERE supplier_email IS NULL OR supplier_email = '') AS null_or_empty_supplier_email,
    COUNT(*) FILTER (WHERE supplier_phone IS NULL OR supplier_phone = '') AS null_or_empty_supplier_phone,
    COUNT(*) FILTER (WHERE supplier_address IS NULL OR supplier_address = '') AS null_or_empty_supplier_address,
    COUNT(*) FILTER (WHERE supplier_city IS NULL OR supplier_city = '') AS null_or_empty_supplier_city,
    COUNT(*) FILTER (WHERE supplier_country IS NULL OR supplier_country = '') AS null_or_empty_supplier_country,
    COUNT(*) FILTER (WHERE customer_first_name IS NULL OR customer_first_name = '') AS null_or_empty_customer_first_name,
    COUNT(*) FILTER (WHERE customer_last_name IS NULL OR customer_last_name = '') AS null_or_empty_customer_last_name,
    COUNT(*) FILTER (WHERE customer_email IS NULL OR customer_email = '') AS null_or_empty_customer_email,
    COUNT(*) FILTER (WHERE customer_country IS NULL OR customer_country = '') AS null_or_empty_customer_country,
    COUNT(*) FILTER (WHERE customer_postal_code IS NULL OR customer_postal_code = '') AS null_or_empty_customer_postal_code,
    COUNT(*) FILTER (WHERE customer_pet_type IS NULL OR customer_pet_type = '') AS null_or_empty_customer_pet_type,
    COUNT(*) FILTER (WHERE customer_pet_name IS NULL OR customer_pet_name = '') AS null_or_empty_customer_pet_name,
    COUNT(*) FILTER (WHERE customer_pet_breed IS NULL OR customer_pet_breed = '') AS null_or_empty_customer_pet_breed,
    COUNT(*) FILTER (WHERE seller_first_name IS NULL OR seller_first_name = '') AS null_or_empty_seller_first_name,
    COUNT(*) FILTER (WHERE seller_last_name IS NULL OR seller_last_name = '') AS null_or_empty_seller_last_name,
    COUNT(*) FILTER (WHERE seller_email IS NULL OR seller_email = '') AS null_or_empty_seller_email
FROM mock_data;